name: "Set up get-tested"
description: "Fetches the get-tested tool"

inputs:
  version:
    description: "The version of the get-tested tool. Defaults to 'latest' if unspecified."
    required: false
    default: ""
  directory:
    description: "The directory where the get-tested executable should be placed."
    required: false
    default: "."

outputs:
  path:
    description: "The path to the get-tested executable."
    value: ${{ steps.setup.outputs.path }}

runs:
  using: "composite"
  steps:
    - name: Set up get-tested
      id: setup
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
        inputs_directory: ${{ inputs.directory }}
        requested_version: ${{ inputs.version }}
      run: bash ./setup-get-tested/setup-get-tested.sh

branding:
  icon: 'list'
  color: 'blue'
