name: "Generate matrix from cabal"

inputs:
  cabal-file:
    description: "The path to your cabal file, e.g. somefolder/myproject.cabal"
    required: true

outputs:
  matrix:
    description: "The GHC version matrix, to be used as `matrix: ${{ fromJSON(needs.your-get-tested-jobname.outputs.matrix) }}`"
    value: ${{ steps.set-matrix.outputs.matrix }}

runs:
  using: "composite"
  steps:
    - name: Checkout base repo
      uses: actions/checkout@v2
    - name: Extract the tested GHC versions
      id: set-matrix
      shell: bash
      run: |
        wget https://github.com/Kleidukos/get-tested/releases/download/v0.1.5.0/get-tested-0.1.5.0-linux-amd64 -O get-tested
        chmod +x get-tested
        ./get-tested --ubuntu --macos ${{ inputs.cabal-file }} >> $GITHUB_OUTPUT

branding:
  icon: 'list'
  color: 'blue'
