name: "Test supported GHC versions"
description: "Generate a test matrix from your cabal file's `tested-with` stanza"

inputs:
  cabal-file:
    description: "The path to your cabal file, e.g. somefolder/myproject.cabal"
    required: true
  windows:
    description: "Enable Windows runner"
    required: false
    default: false
  macos:
    description: "Enable macOS runner"
    required: false
    default: false
  ubuntu:
    description: "Enable Ubuntu runner"
    required: false
    default: false

outputs:
  matrix:
    description: "The GHC version matrix"
    value: ${{ steps.set-matrix.outputs.matrix }}

runs:
  using: "composite"
  steps:
    - name: Checkout base repo
      uses: actions/checkout@v4
    - name: Set up options
      shell: bash
      run: |
        # Extract the version and options
        export version=$(basename $GITHUB_ACTION_PATH | tail -c +2)
        wget -q https://github.com/Kleidukos/get-tested/releases/download/v${version}/get-tested-${version}-linux-amd64 -O get-tested
        chmod +x get-tested

        echo "::debug:: Windows enabled: ${{ inputs.windows }}"
        if [[ ${{ inputs.windows}} = "true" ]]
        then echo "WINDOWS=--windows" >> $GITHUB_ENV
        fi

        echo "::debug:: macOS enabled: ${{ inputs.macos }}"
        if [[ ${{ inputs.macos}} = "true" ]]
        then echo "MACOS=--macos" >> $GITHUB_ENV
        fi

        echo "::debug:: Ubuntu enabled: ${{ inputs.ubuntu }}"
        if [[ ${{ inputs.ubuntu}} = "true" ]]
        then echo "UBUNTU=--ubuntu" >> $GITHUB_ENV
        fi

    - name: Extract the tested GHC versions
      id: set-matrix
      shell: bash
      run: |
        ./get-tested $WINDOWS $MACOS $UBUNTU ${{ inputs.cabal-file }} >> $GITHUB_OUTPUT

branding:
  icon: 'list'
  color: 'blue'
