name: Linting

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  fourmolu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - uses: fourmolu/fourmolu-action@v11
      with:
        pattern: |
          app/**/*.hs
          src/**/*.hs
          test/**/*.hs

  hlint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: 'Set up HLint'
      uses: haskell-actions/hlint-setup@v2
      with:
        version: '3.8'

    - name: 'Run HLint'
      uses: haskell-actions/hlint-run@v2
      with:
        path: '["app", "test", "src"]'
        fail-on: warning
